# 线上配置文件
# @author 阿狸
# yy-api-backend/src/main/resources/application-prod.yml
server:
  port: 8111

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/yy_api?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: yyapi
    password: yyapi123

  redis:
    database: 3
    host: redis
    port: 6379
    password: yyapi@redis
    timeout: 5000

  # 可选：如需 ES 再启用
  # elasticsearch:
  #   uris: http://elasticsearch:9200
  #   username: root
  #   password: 123456

mybatis-plus:
  configuration:
    log-impl: ''  # 关闭 SQL 日志

knife4j:
  basic:
    enable: true
    username: root
    password: 123456

dubbo:
  registry:
    address: nacos://nacos:8848
  protocol:
    name: dubbo
    port: 20882
